server:
  port: 8080
spring:
  devtools:
    restart:
      enabled: true
      additional-paths: src/main/java
      additional-exclude: static/**

  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/order?useSSL=false&characterEncoding=utf-8&useUnicode=true&serverTimezone=Asia/Shanghai
    username: root
    password: root

    # 添加并配置第三方数据源Druid
    # 数据源类型
    type: com.alibaba.druid.pool.DruidDataSource
    # 初始化连接数
    initialSize: 20
    # 最小空闲数
    minIdle: 10
    # 最大连接数
    maxActive: 100


mybatis:
  mapperLocations: classpath:mappers/*Mapper.xml
